import whatsappService from '../services/whatsappService.js';
import qrcode from 'qrcode';

// Enable WhatsApp bot (returns QR code if needed)
export async function enable(req, res) {
  let responded = false;
  const reset = req.query.reset === 'true';
  // Prevent repeated resets: warn if reset is used too often
  if (reset) {
    if (!global.lastWhatsAppReset) global.lastWhatsAppReset = 0;
    const now = Date.now();
    if (now - global.lastWhatsAppReset < 60000) { // 1 minute
      return res.status(429).json({ success: false, error: 'Please wait before resetting WhatsApp session again.' });
    }
    global.lastWhatsAppReset = now;
  }
  try {
    await whatsappService.enableWhatsAppBot(async (qr) => {
      if (responded) return;
      responded = true;
      let qrImageUrl = null;
      let qrToSend = qr;
      try {
        if (!qr) {
          console.error('QR code not generated by Baileys. Sending placeholder.');
          qrToSend = 'PLACEHOLDER-QR-STRING';
        }
        qrImageUrl = await qrcode.toDataURL(qrToSend);
      } catch (qrErr) {
        console.error('Failed to generate QR image:', qrErr);
      }
      if (!qrToSend) {
        res.status(500).json({ success: false, error: 'QR code not generated.' });
      } else {
        res.json({ success: true, message: 'WhatsApp bot enabled.', qr: qrToSend, qrImageUrl });
      }
    }, reset);
    // If the bot is already enabled and no QR is needed, respond immediately
    setTimeout(() => {
      if (!responded) {
        responded = true;
        res.json({ success: true, message: 'WhatsApp bot already enabled.' });
      }
    }, 2000);
  } catch (err) {
    if (!responded) {
      responded = true;
      console.error('Failed to enable WhatsApp bot:', err);
      if (err.name === 'WhatsAppBotError') {
        res.status(500).json({ success: false, error: err.message, code: err.code, details: err.stack });
      } else {
        res.status(500).json({ success: false, error: err.message, details: err.stack });
      }
    }
  }
}

// Disable WhatsApp bot
export function disable(req, res) {
  try {
    whatsappService.disableWhatsAppBot();
    res.json({ success: true, message: 'WhatsApp bot disabled.' });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
}

// Send a test message (for now, takes jid and text)
export async function sendMessage(req, res) {
  try {
    const { jid, text } = req.body;
    if (!jid || !text) return res.status(400).json({ success: false, error: 'jid and text required' });
    await whatsappService.sendWhatsAppMessage(jid, text);
    res.json({ success: true, message: 'Message sent.' });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
}

// TODO: Add endpoints for announcements, group management, chat command handling, Gemini integration, etc. 